language: java

# copy the settings.xml for maven from the "travis" branch
before_install: "git clone -b travis `git config --get remote.origin.url` target/travis"

#script: "mvn --batch-mode -f loader/pom.xml release:update-versions clean deploy --settings target/travis/settings.xml"
script: "mvn -f loader/pom.xml clean deploy --settings target/travis/settings.xml"
script: echo `git config --get remote.origin.url` 
script: mvn --batch-mode -f loader/pom.xml release:update-versions
script: git config --global user.email "${GIT_EMAIL}"
script: git config --global user.name "${GIT_USERNAME}"
script: git config --global user.password "${GIT_PASSWORD}"
script: git add -f loader/pom.xml 
script: git commit -m "update maven version" 
#script: git remote -v
#script: git remote set-url origin https://github.com/lucee/Lucee.git
script: git push origin master

#script: "mvn --batch-mode -f loader/pom.xml release:update-versions --settings target/travis/settings.xml"
#script: git commit -m "commit from travis"
#script: $ git push -u origin master

#script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -f loader/pom.xml clean deploy --settings target/travis/settings.xml || mvn -f loader/pom.xml clean install"

# oldscript: mvn -f loader/pom.xml clean deploy

# whitelist
branches:
  only:
    - master

#deploy:
#	skip_cleanup: true

after_success:
- mvn --batch-mode -f loader/pom.xml release:update-versions
- git config --global user.email "${GIT_EMAIL}"
- git config --global user.name "${GIT_USERNAME}"
- git config --global user.password "${GIT_PASSWORD}"
- git add -f loader/pom.xml 
- git commit -m "update maven version" 
- git remote -v
#- "git remote set-url origin `git config --get remote.origin.url`"
- git remote set-url origin https://github.com/lucee/Lucee.git
- git push

notifications:
  slack: luceeserver:ZTfbu4bVSLFmakRcLInrNZIT
  email:
    - michael@lucee.org

